import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

// Tokens copied 1:1 from the Stitch "Regal Modernity" design system (DESIGN.md / code.html)
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#4e051a',
        'tertiary-fixed-dim': '#d8c3aa',
        'surface-container-highest': '#e4e2e1',
        'error-container': '#ffdad6',
        'surface-container': '#f0eded',
        'on-secondary-fixed-variant': '#5f4018',
        'tertiary-container': '#453825',
        tertiary: '#2e2312',
        'on-secondary-container': '#79572c',
        'on-error': '#ffffff',
        'on-background': '#1b1c1c',
        'on-tertiary-fixed-variant': '#524531',
        surface: '#fcf9f8',
        'outline-variant': '#dac0c2',
        'on-primary-fixed-variant': '#7c2a3b',
        'secondary-container': '#fecf9a',
        'on-secondary-fixed': '#2b1700',
        'surface-bright': '#fcf9f8',
        secondary: '#7a582d',
        'surface-variant': '#e4e2e1',
        'surface-container-high': '#eae7e7',
        error: '#ba1a1a',
        'surface-container-low': '#f6f3f2',
        'on-tertiary': '#ffffff',
        'on-primary': '#ffffff',
        'on-surface-variant': '#544244',
        'on-primary-container': '#ee8495',
        'on-error-container': '#93000a',
        'secondary-fixed': '#ffddb8',
        'on-surface': '#1b1c1c',
        'surface-tint': '#9a4152',
        'on-tertiary-container': '#b4a189',
        'secondary-fixed-dim': '#ecbe8b',
        'surface-container-lowest': '#ffffff',
        background: '#fcf9f8',
        'primary-fixed': '#ffd9dd',
        'inverse-surface': '#303030',
        'on-primary-fixed': '#400013',
        'primary-container': '#6b1d2f',
        'inverse-on-surface': '#f3f0f0',
        'surface-dim': '#dcd9d9',
        'on-tertiary-fixed': '#241a09',
        'tertiary-fixed': '#f5dfc5',
        outline: '#877274',
        'on-secondary': '#ffffff',
        'primary-fixed-dim': '#ffb2bc',
        'inverse-primary': '#ffb2bc',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '1.5rem',
        'space-xl': '3rem',
        'space-lg': '1.75rem',
        'gutter-mobile': '1rem',
        'space-sm': '0.5rem',
        'space-xs': '0.25rem',
        'space-md': '1rem',
        'margin-mobile': '1.25rem',
        margin: '4rem',
      },
      fontFamily: {
        'display-lg-mobile': ['Playfair Display', 'Georgia', 'serif'],
        'headline-sm': ['Playfair Display', 'Georgia', 'serif'],
        'display-lg': ['Playfair Display', 'Georgia', 'serif'],
        'title-lg': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'title-md': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'headline-md': ['Playfair Display', 'Georgia', 'serif'],
        'headline-lg': ['Playfair Display', 'Georgia', 'serif'],
        'label-lg': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'body-sm': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'label-md': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'headline-lg-mobile': ['Playfair Display', 'Georgia', 'serif'],
      },
      fontSize: {
        'display-lg-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'headline-sm': ['22px', { lineHeight: '30px', fontWeight: '500' }],
        'display-lg': ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '400' }],
        'title-lg': ['18px', { lineHeight: '26px', letterSpacing: '0.01em', fontWeight: '600' }],
        'title-md': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'body-md': ['15px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['28px', { lineHeight: '36px', fontWeight: '500' }],
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'label-lg': ['12px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['11px', { lineHeight: '14px', letterSpacing: '0.06em', fontWeight: '500' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '400' }],
      },
    },
  },
  plugins: [forms, containerQueries],
};
